//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SearchPrototype.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCompany
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblCompany()
        {
            this.tblLocationsToCompanies = new HashSet<tblLocationsToCompany>();
            this.tblSpecialitiesToCompanies = new HashSet<tblSpecialitiesToCompany>();
        }
    
        public int intID { get; set; }
        public string strName { get; set; }
        public string strWebsite { get; set; }
        public string strSize { get; set; }
        public string strLinkedInUrl { get; set; }
        public int intLinkedInID { get; set; }
        public int intCategoryID { get; set; }
        public string strContactPhone { get; set; }
        public string strContactEmail { get; set; }
        public string strTwitterID { get; set; }
    
        public virtual tblCategory tblCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblLocationsToCompany> tblLocationsToCompanies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSpecialitiesToCompany> tblSpecialitiesToCompanies { get; set; }
    }
}
