//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SearchPrototype.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSpeciality
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblSpeciality()
        {
            this.tblSpecialitiesToCompanies = new HashSet<tblSpecialitiesToCompany>();
        }
    
        public int intID { get; set; }
        public string strName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSpecialitiesToCompany> tblSpecialitiesToCompanies { get; set; }
    }
}
